# https://docs.spring.io/spring-boot/docs/2.0.3.RELEASE/reference/html/common-application-properties.html

# 指定输出pid的位置
# spring.pid.file: app.pid 

# 自定义参数 for SpringAnnotation1
# 这个前缀似乎不能含有大写字母
springannotation1.aaa : aaa
springannotation1.bbb : 123


# 自定义参数 for SpringAnnotation2
# springAnnotation2.value : 
springAnnotation2.names : aaa,bbb,ccc,ddd

# AOP
# 是否支持@EnableAspectJAutoProxy，默认为: true
spring.aop.auto: true
# true为使用CGLIB代理，需要自己引入jar包，false为JDK代理，默认为false
spring.aop.proxy-target-class: true