# https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/common-application-properties.html

# server
server.port: 9090
server.servlet.context-path: /sbw

# AOP
# 是否支持@EnableAspectJAutoProxy，默认为: true
spring.aop.auto: true
# true为使用CGLIB代理，需要自己引入jar包，false为JDK代理，默认为false
spring.aop.proxy-target-class: true

# JDBC
spring.datasource.url: jdbc:mysql://localhost:3306/springbootweb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# 请查看pom文件中的注解，说明 jdbc pool的使用顺序
# HikariCP settings
# spring.datasource.hikari.*

# 在 com.zaxxer.hikari.HikariConfig类中，能查看到很多属性及其默认值

#60 sec
spring.datasource.hikari.connection-timeout: 60000
# max 5
spring.datasource.hikari.maximum-pool-size: 5
# 连接检测
spring.datasource.hikari.connection-test-query: select 1

# mybatis
# mapper.xml所在的位置
mybatis.mapper-locations: classpath:mybatis/sqlmap/*.xml
# entity扫描的包名
mybatis.type-aliases-package: com.sauzny.springbootweb.entity.pojo

# 打印sql
logging.level.com.sauzny.springbootweb.dao: debug

# pagehelper
pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params: count=countSql

# ====================springbootadmin====================
spring.boot.admin.client.url: http://localhost:8000
spring.boot.admin.client.name: springbootweb
spring.boot.admin.client.username: admin
spring.boot.admin.client.password: admin
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: ALWAYS

# ====================sbw system====================
audience.base64Secret: sbwjwtSecret
audience.expiresSecond: 864000
audience.needCaptcha: false
audience.needjump: true
audience.jumppassword: jump



# ProductionSecurityFilter:开启生产环境,屏蔽所有Swagger资源,不可访问,production配置为true时,basic认证功能不可用
swagger.production: true


# SecurityBasicAuthFilter：开启HTTP Basic认证,访问Swagger资源需要提供服务端配置的用户名以及密码

## 开启Swagger的Basic认证功能,默认是false
swagger.basic.enable: true
## Basic认证用户名
swagger.basic.username: zhangsan
## Basic认证密码
swagger.basic.password: 123


example.service:
  enabled: true
  prefix: ppp
  suffix: sss